// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvLPxK61a-LuyVFlfNnKQrmDNT3Q1nu44',
    appId: '1:956967089057:web:bd6f38b3ad6950706111e0',
    messagingSenderId: '956967089057',
    projectId: 'foody-1025d',
    authDomain: 'foody-1025d.firebaseapp.com',
    storageBucket: 'foody-1025d.appspot.com',
    measurementId: 'G-SZCWYHZBBP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDevxL2rXPOguQS_ybYAO08qk6PZynndis',
    appId: '1:956967089057:android:f5c26cf19b174bbd6111e0',
    messagingSenderId: '956967089057',
    projectId: 'foody-1025d',
    storageBucket: 'foody-1025d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYFFkMWHETp8nHY0TEvDMeWEfCkCdE5Ws',
    appId: '1:956967089057:ios:db6893f50d0535cd6111e0',
    messagingSenderId: '956967089057',
    projectId: 'foody-1025d',
    storageBucket: 'foody-1025d.appspot.com',
    iosBundleId: 'com.example.foody',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYFFkMWHETp8nHY0TEvDMeWEfCkCdE5Ws',
    appId: '1:956967089057:ios:db6893f50d0535cd6111e0',
    messagingSenderId: '956967089057',
    projectId: 'foody-1025d',
    storageBucket: 'foody-1025d.appspot.com',
    iosBundleId: 'com.example.foody',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvLPxK61a-LuyVFlfNnKQrmDNT3Q1nu44',
    appId: '1:956967089057:web:6b23e1920bc5aaa46111e0',
    messagingSenderId: '956967089057',
    projectId: 'foody-1025d',
    authDomain: 'foody-1025d.firebaseapp.com',
    storageBucket: 'foody-1025d.appspot.com',
    measurementId: 'G-TRK6WT6222',
  );

}